/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Gustav
 */
public class RedigeraAlienAgent extends javax.swing.JFrame {
    
    private InfDB idb;
    //Sträng som används för att visa vem som är inloggad.
     private String loginID;
    /**
     * Creates new form RedigeraAlien
     */
    public RedigeraAlienAgent(InfDB idb, String loginID) {
        initComponents();
        this.idb = idb;
        this.loginID = loginID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVerkstallAlien = new javax.swing.JButton();
        cbAndraAlien = new javax.swing.JComboBox<>();
        txtAngeAlienID = new javax.swing.JTextField();
        txtNyttVardeAlien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnVerkstallAgent = new javax.swing.JButton();
        cbAndraAgent = new javax.swing.JComboBox<>();
        txtAngeAgentID = new javax.swing.JTextField();
        txtNyttVardeAgent = new javax.swing.JTextField();
        lblAgentID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Redigera alien");

        btnVerkstallAlien.setText("Verkställ");
        btnVerkstallAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerkstallAlienActionPerformed(evt);
            }
        });

        cbAndraAlien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registreringsdatum", "Lösenord", "Namn", "Telefonnummer", "Plats", "Ansvarig agent" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ange alien-ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Välj vad du vill ändra");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ange nytt värde");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Redigera agent");

        btnVerkstallAgent.setText("Verkställ");
        btnVerkstallAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerkstallAgentActionPerformed(evt);
            }
        });

        cbAndraAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Namn", "Telefonnummer", "Anställningsdatum", "Administratörsstatus", "Lösenord", "Område" }));

        txtAngeAgentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngeAgentIDActionPerformed(evt);
            }
        });

        lblAgentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAgentID.setText("Ange agent-ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Välj vad du vill ändra");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ange nytt värde");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbAndraAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAngeAlienID, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNyttVardeAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerkstallAlien)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAndraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAngeAgentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(lblAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNyttVardeAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerkstallAgent)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAngeAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAndraAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNyttVardeAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerkstallAlien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblAgentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAngeAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbAndraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNyttVardeAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerkstallAgent))
                        .addGap(55, 55, 55))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerkstallAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerkstallAlienActionPerformed
        if(Validering.kollaOmAlienFinns(txtAngeAlienID)){
        String sqlFraga = "";
        String id = txtAngeAlienID.getText();
        String valdAndring = (String) cbAndraAlien.getSelectedItem();
        String nyttVarde = txtNyttVardeAlien.getText();
        boolean valideringLyckad = false;
        if (null != valdAndring)switch (valdAndring) {
                case "Registreringsdatum":
                    if(Validering.kollaDatumFormat(txtNyttVardeAlien)) {
                        sqlFraga = "UPDATE alien SET registreringsdatum = '" + nyttVarde + "' WHERE alien_id = '" + id + "';";
                         valideringLyckad = true;
                    }           break;
                case "Lösenord":
                    if(Validering.kollaLosenordLangd(txtNyttVardeAlien)) {
                        sqlFraga = "UPDATE alien SET losenord = '" + nyttVarde + "' WHERE alien_id = '" + id + "';";
                         valideringLyckad = true;
                    }           break;
                case "Namn":
                    if(Validering.kollaNamnFormat(txtNyttVardeAlien)) {
                        sqlFraga = "UPDATE alien SET namn = '" + nyttVarde + "' WHERE alien_id = '" + id + "';";
                         valideringLyckad = true;
                    }           break;
                case "Telefonnummer":
                    if(Validering.kollaTelefonFormat(txtNyttVardeAlien)) {
                        sqlFraga = "UPDATE alien SET telefon = '" + nyttVarde + "' WHERE alien_id = '" + id + "';";
                         valideringLyckad = true;
                    }           break;
                case "Plats":
                    if(Validering.kollaOmPlatsFinns(txtNyttVardeAlien)) {
                        sqlFraga = "UPDATE alien SET plats = '" + nyttVarde + "' WHERE alien_id = '" + id + "';";
                         valideringLyckad = true;
                    }           break;
                case "Ansvarig agent":
                    if(Validering.kollaOmAgentFinns(txtNyttVardeAlien)) {
                        sqlFraga = "UPDATE alien SET ansvarig_agent = '" + nyttVarde + "' WHERE alien_id = '" + id + "';";
                         valideringLyckad = true;
                    }           break;
                default:
                    nyttVarde = "";
                    break;
            }
        if(!valideringLyckad) {
            nyttVarde = "";
        }
        if (nyttVarde != null && !nyttVarde.trim().isEmpty()) {
        try {
            idb.update(sqlFraga);
            JOptionPane.showMessageDialog(null, "Uppdatering lyckades.");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel: " + ex.getMessage());
        }
    } 
    }
        
    }//GEN-LAST:event_btnVerkstallAlienActionPerformed

    private void btnVerkstallAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerkstallAgentActionPerformed
        if(Validering.kollaOmAgentFinns(txtAngeAgentID)){
        String sqlFraga = "";
        String id = (String) txtAngeAgentID.getText();
        String valdAndring = (String) cbAndraAgent.getSelectedItem();
        String nyttVarde = (String) txtNyttVardeAgent.getText();
        boolean valideringLyckad = false;

        if (null != valdAndring)switch (valdAndring) {
                case "Namn":
                    if(Validering.kollaNamnFormat(txtNyttVardeAgent)) {
                        sqlFraga = "UPDATE agent SET namn = '" + nyttVarde + "' WHERE agent_id = " + id + ";";
                         valideringLyckad = true;
                    }      break;
                case "Telefonnummer":
                    if(Validering.kollaTelefonFormat(txtNyttVardeAgent)) {
                        sqlFraga = "UPDATE agent SET telefon = '" + nyttVarde + "' WHERE agent_id = " + id + ";";
                         valideringLyckad = true;
                    }      break;
                case "Anställningsdatum":
                    if(Validering.kollaDatumFormat(txtNyttVardeAgent)) {
                        sqlFraga = "UPDATE agent SET anstallningsdatum = '" + nyttVarde + "' WHERE agent_id = " + id + ";";
                         valideringLyckad = true;
                    }          break;
                case "Administratörsstatus":
                    if(!id.equals(loginID)) {
                    if(nyttVarde.equals("J") || nyttVarde.equals("N")) {
                        sqlFraga = "UPDATE agent SET administrator = '" + nyttVarde + "' WHERE agent_id = " + id + ";";
                         valideringLyckad = true;
                    }
                    else {
                        nyttVarde = "";
                        JOptionPane.showMessageDialog(null, "Ange endast J eller N som adminstatus.");
                    } } else {
                    JOptionPane.showMessageDialog(null, "Du kan inte redigera din egna administratörsstatus.");}          break;
                case "Lösenord":
                    if(Validering.kollaLosenordLangd(txtNyttVardeAgent)) {
                        sqlFraga = "UPDATE agent SET losenord = '" + nyttVarde + "' WHERE agent_id = " + id + ";";
                        valideringLyckad = true;
                    }          break;
                case "Område":
                    if(Validering.kollaOmOmradeFinns(txtNyttVardeAgent)) {
                        sqlFraga = "UPDATE agent SET omrade = '" + nyttVarde + "' WHERE agent_id = " + id + ";";
                        valideringLyckad = true;
                    }          break;
                default:
                    break;
            }
        if(!valideringLyckad) {
            nyttVarde = "";
        }
        if (nyttVarde != null && !nyttVarde.trim().isEmpty()) {
        try {
            idb.update(sqlFraga);
            JOptionPane.showMessageDialog(null, "Uppdatering lyckades.");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel: " + ex.getMessage());
            System.out.println("Internt felmeddelande:" + ex);
        }
    }
        }
    }//GEN-LAST:event_btnVerkstallAgentActionPerformed

    private void txtAngeAgentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngeAgentIDActionPerformed

    }//GEN-LAST:event_txtAngeAgentIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlienAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlienAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlienAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraAlienAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerkstallAgent;
    private javax.swing.JButton btnVerkstallAlien;
    private javax.swing.JComboBox<String> cbAndraAgent;
    private javax.swing.JComboBox<String> cbAndraAlien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgentID;
    private javax.swing.JTextField txtAngeAgentID;
    private javax.swing.JTextField txtAngeAlienID;
    private javax.swing.JTextField txtNyttVardeAgent;
    private javax.swing.JTextField txtNyttVardeAlien;
    // End of variables declaration//GEN-END:variables
}
