/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Gustav, Neryse, Oskar
 */
public class RegistreraUtrustning extends javax.swing.JFrame {

    private InfDB idb;

    // Deklarerar och instansierar databasuppkoppling
    public RegistreraUtrustning(InfDB idb) {
        // Deklarerar instans av databasuppkoppling
        this.idb = idb;
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUtrustningsID = new javax.swing.JLabel();
        lblUtrustningsBenamning = new javax.swing.JLabel();
        lblRegistreraUtrustning = new javax.swing.JLabel();
        lblUtrustningsTyp = new javax.swing.JLabel();
        cbUtrustningsTyp = new javax.swing.JComboBox<>();
        txtUtrustningsID = new javax.swing.JTextField();
        txtUtrustningsBenamning = new javax.swing.JTextField();
        lblRegistreringsBeskrivning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUtrustningsID.setText("Utrustningens ID:");

        lblUtrustningsBenamning.setText("Benämning:");

        lblRegistreraUtrustning.setText("Registrera utrustning");

        lblUtrustningsTyp.setText("Utrustningstyp:");

        cbUtrustningsTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vapen", "Teknik", "Kommunikation" }));
        cbUtrustningsTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUtrustningsTypActionPerformed(evt);
            }
        });

        txtUtrustningsID.setText("1");

        txtUtrustningsBenamning.setText("Cool utrustning");

        lblRegistreringsBeskrivning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegistreringsBeskrivning.setText("Utrustningen läggs till när du valt utrustningstyp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUtrustningsID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUtrustningsTyp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbUtrustningsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUtrustningsBenamning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUtrustningsBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblRegistreraUtrustning))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegistreringsBeskrivning)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRegistreraUtrustning)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustningsID)
                    .addComponent(txtUtrustningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustningsBenamning)
                    .addComponent(txtUtrustningsBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustningsTyp)
                    .addComponent(cbUtrustningsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistreringsBeskrivning)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbUtrustningsTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUtrustningsTypActionPerformed
        // Kollar först så textfälten har värden och om nödvändigt, är heltal.
        if (Validering.kollaUniktIDUtrustning(txtUtrustningsID) && Validering.textFaltHarVarde(txtUtrustningsBenamning)) {
            // Sätter en maxlängd på utrustningens benämning för att stämma överens med databasstrukturen
            int benamningMaxLangd = 20;

            if (txtUtrustningsBenamning.getText().length() < benamningMaxLangd) {
                // Hämtar värden från textrutor och combobox och deklarerar deras värden som strängar.
                String nyttUtrustningsID = txtUtrustningsID.getText();
                String nyttUtrustningsBenamning = txtUtrustningsBenamning.getText();
                String valdTyp = (String) cbUtrustningsTyp.getSelectedItem();
                // Deklarerar strängar för fråga och input för att kunna dynamiskt ändra dem vid switch case
                String sqlFraga = "";
                String input = "";
                // Börjar med att lägga till ny utrustning i databasen
                String sqlUnikUtrustningFraga = "INSERT INTO utrustning (utrustnings_id, benamning) VALUES (" + nyttUtrustningsID + ", '" + nyttUtrustningsBenamning + "')";
                try {
                    idb.insert(sqlUnikUtrustningFraga);

                    // Om en typ har valts i comboboxen
                    if (null != valdTyp) {
                        // Vid varje valt case så bestämmer sqlfrågan vilken typ av utrustning det är, och bestämmer då rätt tabell för att lägga detta i.
                        switch (valdTyp) {
                            // När case är "Vapen", skapa en inputruta som frågar om kaliber
                            case "Vapen":
                                input = JOptionPane.showInputDialog(this, "Ange antal kaliber:");
                                sqlFraga = "INSERT INTO vapen (utrustnings_id, kaliber) VALUES ('" + nyttUtrustningsID + "', '" + input + "');";
                                break;
                            case "Teknik":
                                // När case är "Teknik", skapa en inputruta som frågar om kraftkälla
                                input = JOptionPane.showInputDialog(this, "Ange kraftkälla:");
                                sqlFraga = "INSERT INTO teknik (utrustnings_id, kraftkalla) VALUES ('" + nyttUtrustningsID + "', '" + input + "');";
                                break;
                            case "Kommunikation":
                                // När case är "Kommunikation", skapa en inputruta som frågar om överföringsteknik
                                input = JOptionPane.showInputDialog(this, "Ange överföringsteknik:");
                                sqlFraga = "INSERT INTO kommunikation (utrustnings_id, overforingsteknik) VALUES ('" + nyttUtrustningsID + "', '" + input + "');";
                                break;
                            default:
                                break;
                        }

                        // Om användaren matade in ett värde på inputrutan som dök upp.
                        if (input != null && !input.trim().isEmpty()) {
                            try {
                                // Matar in typen av utrustning i rätt tabell och ger ett övergripande meddelande som berättar att allt fungerade
                                idb.insert(sqlFraga);
                                JOptionPane.showMessageDialog(null, "Utrustning lades till i systemet.");
                            } catch (InfException ex) {
                                JOptionPane.showMessageDialog(null, "Något gick fel");
                                System.out.println("Internt felmeddelande: " + ex.getMessage());
                            }
                        } else {
                            // Om "input" är tom
                            JOptionPane.showMessageDialog(null, "Textfältet kan inte vara tomt!");
                        }
                    }
                } catch (InfException ex) {
                    //Vid oväntat fel, visa felmeddelande.
                    JOptionPane.showMessageDialog(null, "Något gick fel");
                    System.out.println("Internt felmeddelande: " + ex.getMessage());
                }
            } else {
                // Om benämningsbeskrivningen överskred 20 tecken
                JOptionPane.showMessageDialog(null, "Benämningsbeskrivningen är för lång.");
            }
        }
    }//GEN-LAST:event_cbUtrustningsTypActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbUtrustningsTyp;
    private javax.swing.JLabel lblRegistreraUtrustning;
    private javax.swing.JLabel lblRegistreringsBeskrivning;
    private javax.swing.JLabel lblUtrustningsBenamning;
    private javax.swing.JLabel lblUtrustningsID;
    private javax.swing.JLabel lblUtrustningsTyp;
    private javax.swing.JTextField txtUtrustningsBenamning;
    private javax.swing.JTextField txtUtrustningsID;
    // End of variables declaration//GEN-END:variables
}
